---
title: Reproduce Classic Papers - Prevalence of coronary heart disease risk factors among rural blacks
author: Giacomo Bianchi
date: '2017-09-16'
output:
    html_document:
        theme: default
        highlight: default
        toc: true
        toc_float: true
slug: CAD in Rural Blacks
categories:
  - R
  - Data Analysis
  - Cardiology
  - Classic Pepers
tags:
  - Data Analysis
  - Tidy Data
  - Data Munging
  - R Notebook
---

#Classic Paper: Prevalence of CAD in Rural Blacks


#Data retrieve

```{r Load Libraries, message=FALSE, warning=FALSE, paged.print=FALSE}
library(tidyverse)
library(Hmisc)
library(ggmap)
library(ggrepel)
```
The dataset is present at Vanderbilt University server and can be easily retrieved using the function `getHdata()` from the `Hmisc` library.

```{r Dataset retrieve}
getHdata(diabetes)
diabetes <- as_tibble(diabetes)
```

```{r get the map}
locations <- levels(diabetes$location)
locations <- paste0(locations, ", VA, USA")
poi1 <-  geocode(locations[1], source = "google")
poi2 <- geocode(locations[2], source = "google")
loc_list <- rbind(poi1, poi2)
paper_map <- qmap("Virginia", zoom = 8, maptype = 'toner-hybrid', source = 'stamen')

paper_map +
    geom_point(aes(x = lon, y = lat), col = "red", size = 3,
               data = loc_list) +
    geom_text_repel(aes(x = lon, y = lat, label = locations),
                    hjust = 0.5,
                    vjust = -1,
                    data = loc_list) +
    ggtitle("Map of Cities in the Study")
    

```


```{r Explore the dataset}
html(contents(diabetes))
glimpse(diabetes)
```


```{r}
diabetes %>% group_by(gender) %>%
    summarise(n(), Mean_age = mean(age), Mean_height = mean(height*2.14, na.rm = T))
```

```{r}
na.omit(diabetes) %>% 
    ggplot(aes(x = frame, y = waist*2.54, fill = gender)) +
        geom_boxplot()
```

```{r}
na.omit(diabetes) %>%
    ggplot(aes(stab.glu, glyhb, fill = frame, color = gender)) +
        geom_point(shape = 21, alpha = 0.6, size = 3) 
        #scale_x_log10()
```



